sudo: required
services:
  - docker

before_install:
  - docker run build -t liam/docker-aws-ci-test -f Dockerfile.dev .

script:
  - docker run -e CI=true liam/docker-aws-ci-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"